/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis;

/**
 *
 * @author Asus
 */
public class kuiss extends javax.swing.JFrame {

    /**
     * Creates new form kuiss
     */
    public kuiss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        nama1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        absen1 = new java.awt.TextField();
        matpel1 = new java.awt.TextField();
        nilai1 = new java.awt.TextField();
        prozez = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Penilaian Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 11, 93, 15);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Absen");
        getContentPane().add(label1);
        label1.setBounds(107, 66, 40, 20);

        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama1);
        nama1.setBounds(164, 36, 108, 20);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Matpel");
        getContentPane().add(label2);
        label2.setBounds(107, 96, 42, 20);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Nama");
        getContentPane().add(label3);
        label3.setBounds(107, 36, 37, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Nilai");
        getContentPane().add(label4);
        label4.setBounds(107, 126, 28, 20);

        absen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absen1ActionPerformed(evt);
            }
        });
        getContentPane().add(absen1);
        absen1.setBounds(164, 66, 108, 20);

        matpel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matpel1ActionPerformed(evt);
            }
        });
        getContentPane().add(matpel1);
        matpel1.setBounds(164, 96, 108, 20);

        nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilai1ActionPerformed(evt);
            }
        });
        getContentPane().add(nilai1);
        nilai1.setBounds(164, 126, 108, 20);

        prozez.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prozez.setText("Proses");
        prozez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prozezMouseReleased(evt);
            }
        });
        prozez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prozezActionPerformed(evt);
            }
        });
        getContentPane().add(prozez);
        prozez.setBounds(174, 156, 71, 23);

        jPanel1.setLayout(null);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(122, 193, 166, 96);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    private void absen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absen1ActionPerformed

    private void matpel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matpel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matpel1ActionPerformed

    private void nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilai1ActionPerformed

    private void prozezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prozezActionPerformed
        // TODO add your handling code here:
        String Nama = nama1.getText();
        String Absen = absen1.getText();
        String Matpel = matpel1.getText();
        int Nilai = Integer.parseInt(nilai1.getText());
        String Keterangan="";
        
        if (Nilai >= 75) {
            Keterangan="Lulus";
        }else if (Nilai<75) {
            Keterangan="Tidak Lulus";
        }else if (Nilai > 100){
            Keterangan = "Sempurna";
        }else if (Nilai > 102){
            Keterangan = "Amazing";
        }

        hasil.setText("Nama siswa : "+Nama+"\n"+"Absen : "+Absen+"\n"+"Matpel : "+Matpel+"\n"+"Nilai :"+Nilai+"\nKeterangan:"+Keterangan);
    }//GEN-LAST:event_prozezActionPerformed

    private void prozezMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prozezMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_prozezMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuiss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField absen1;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField matpel1;
    private java.awt.TextField nama1;
    private java.awt.TextField nilai1;
    private javax.swing.JButton prozez;
    // End of variables declaration//GEN-END:variables
}
