/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form latihan2
     */
    public latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Formulir = new java.awt.Label();
        nama = new java.awt.TextField();
        label1 = new java.awt.Label();
        alamat = new java.awt.TextField();
        absen = new java.awt.TextField();
        kelas = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        OKE = new java.awt.Button();
        TA = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Formulir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Formulir.setText("Formulir");
        getContentPane().add(Formulir);
        Formulir.setBounds(170, 10, 80, 28);
        getContentPane().add(nama);
        nama.setBounds(130, 50, 190, 20);

        label1.setText("Nama");
        getContentPane().add(label1);
        label1.setBounds(80, 50, 38, 20);
        getContentPane().add(alamat);
        alamat.setBounds(130, 140, 190, 20);
        getContentPane().add(absen);
        absen.setBounds(130, 80, 190, 20);
        getContentPane().add(kelas);
        kelas.setBounds(130, 110, 190, 20);

        label2.setText("Absen");
        getContentPane().add(label2);
        label2.setBounds(80, 80, 39, 20);

        label3.setText("Kelas");
        getContentPane().add(label3);
        label3.setBounds(80, 110, 36, 20);

        label4.setText("Alamat");
        getContentPane().add(label4);
        label4.setBounds(80, 140, 42, 20);

        OKE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OKE.setLabel("OKE");
        OKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKEActionPerformed(evt);
            }
        });
        getContentPane().add(OKE);
        OKE.setBounds(190, 180, 46, 27);
        getContentPane().add(TA);
        TA.setBounds(80, 230, 280, 110);

        setBounds(0, 0, 416, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void OKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKEActionPerformed
        // TODO add your handling code here:
        String Nama = nama.getText();
        String Absen = absen.getText();
        String Kelas = kelas.getText();
        String Alamat = alamat.getText();
        
        TA.setText("Nama siswa : "+Nama+"\n"+"Absen : "+Absen+"\n"+"Kelas : "+Kelas+"\n"+"Alamat siswa : "+Alamat);
    }//GEN-LAST:event_OKEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Formulir;
    private java.awt.Button OKE;
    private java.awt.TextArea TA;
    private java.awt.TextField absen;
    private java.awt.TextField alamat;
    private java.awt.TextField kelas;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField nama;
    // End of variables declaration//GEN-END:variables
}
