/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan3;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form volume
     */
    public latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        panjang1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitung1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volume = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel8.setLayout(null);

        panjang1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panjang1.setText("Masukkan Panjang :");
        jPanel8.add(panjang1);
        panjang1.setBounds(10, 14, 113, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan Lebar      :");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(10, 52, 114, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan Tinggi     :");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(10, 93, 113, 14);
        jPanel8.add(Panjang);
        Panjang.setBounds(141, 11, 31, 20);
        jPanel8.add(Lebar);
        Lebar.setBounds(142, 49, 30, 20);
        jPanel8.add(Tinggi);
        Tinggi.setBounds(141, 87, 31, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("cm");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(176, 14, 17, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("cm");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(176, 52, 17, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("cm");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(176, 90, 17, 14);

        hitung1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hitung1.setText("Hitung");
        hitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung1ActionPerformed(evt);
            }
        });
        jPanel8.add(hitung1);
        hitung1.setBounds(141, 125, 69, 23);

        jTabbedPane1.addTab("Balok", jPanel8);

        jPanel9.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(10, 11, 129, 14);
        jPanel9.add(Sisi);
        Sisi.setBounds(10, 36, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("cm");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(94, 39, 17, 14);

        volume.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        volume.setText("Volume");
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });
        jPanel9.add(volume);
        volume.setBounds(10, 74, 75, 23);

        jTabbedPane1.addTab("Kubus", jPanel9);

        jPanel10.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari - Jari");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 11, 163, 14);
        jPanel10.add(jari);
        jari.setBounds(10, 31, 67, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("cm");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(81, 34, 17, 14);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);
        jButton2.setBounds(10, 69, 75, 23);

        jTabbedPane1.addTab("Bola", jPanel10);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 37, 400, 270);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Progam Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(83, 11, 218, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung1ActionPerformed
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah : "+hasil, "Luas : ", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitung1ActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan Kubus Adalah: "+hasil, "Luas : ", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_volumeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float Jari;
        Jari = Integer.parseInt(jari.getText());
        float hasil = (float)(4/3*3.14*Jari*Jari*Jari);
        try{
            JOptionPane.showMessageDialog(null, "Luas Permukaan Bola Adalah: "+hasil, "Luas : ", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton hitung1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jari;
    private javax.swing.JLabel panjang1;
    private javax.swing.JButton volume;
    // End of variables declaration//GEN-END:variables
}
