
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class uji extends javax.swing.JFrame {

    /**
     * Creates new form uji
     */
    public uji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tinggi1 = new javax.swing.JTextField();
        berat1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cewek = new javax.swing.JRadioButton();
        lakii = new javax.swing.JRadioButton();
        hitung1 = new javax.swing.JButton();
        coba1 = new javax.swing.JButton();
        keluarr = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ini1 = new javax.swing.JTextField();
        ini2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setForeground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(176, 11, 97, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(67, 46, 32, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(67, 72, 34, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(67, 98, 69, 14);

        jk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jk.setText("Jenis Kelamin");
        jPanel1.add(jk);
        jk.setBounds(67, 121, 77, 14);
        jPanel1.add(nama1);
        nama1.setBounds(176, 43, 174, 20);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 69, 0, 0);
        jPanel1.add(tinggi1);
        tinggi1.setBounds(176, 69, 33, 20);
        jPanel1.add(berat1);
        berat1.setBounds(176, 95, 33, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(213, 72, 17, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("kg");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(213, 98, 14, 14);

        cewek.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cewek.setText("Perempuan");
        jPanel1.add(cewek);
        cewek.setBounds(176, 117, 91, 23);

        lakii.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lakii.setText("Laki - Laki");
        jPanel1.add(lakii);
        lakii.setBounds(267, 117, 83, 23);

        hitung1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hitung1.setText("Hitung");
        hitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung1ActionPerformed(evt);
            }
        });
        jPanel1.add(hitung1);
        hitung1.setBounds(67, 158, 69, 23);

        coba1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        coba1.setText("Coba Lagi");
        coba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coba1ActionPerformed(evt);
            }
        });
        jPanel1.add(coba1);
        coba1.setBounds(154, 158, 87, 23);

        keluarr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keluarr.setText("Keluar");
        keluarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarrActionPerformed(evt);
            }
        });
        jPanel1.add(keluarr);
        keluarr.setBounds(259, 158, 69, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Berat badan ideal anda adalah");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(67, 202, 171, 14);
        jPanel1.add(Ideal);
        Ideal.setBounds(256, 199, 37, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("kg");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(311, 202, 14, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Hasil Diagnosa Kesehatan");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 230, 145, 14);
        jPanel1.add(ini1);
        ini1.setBounds(31, 250, 329, 20);
        jPanel1.add(ini2);
        ini2.setBounds(30, 270, 330, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung1ActionPerformed
        // TODO add your handling code here:
        try{
        int tinggi = Integer.parseInt(tinggi1.getText());
        int berat = Integer.parseInt(berat1.getText());
        String nama = nama1.getText();
        int ideal = 0;
        if(cewek.isSelected()){
            ideal = tinggi - 100;
        }else if (lakii.isSelected()){
            ideal = tinggi - 104;
        }
        String temp = Integer.toString(ideal);
        if(ideal <  berat){
            Ideal.setText(temp);
            ini1.setText("Maaf"+nama+", Sepertinya Anda overweigth :( ");
            ini2.setText("Banyaklah olahraga dan hindari makanan berkolesterol");
        }else  if(ideal >  berat){
            Ideal.setText(temp);
            ini1.setText("Maaf"+nama+", Sepertinya Anda overweigth :( ");
            ini2.setText("Banyaklah olahraga dan hindari makanan berkolesterol");
        }else{
            Ideal.setText(temp);
            ini1.setText("Halo"+nama+", Good Job berat badan Anda sudah ideal");
            ini2.setText("Banyaklah olahraga dan hindari makanan berkolesterol");
        }
    }//GEN-LAST:event_hitung1ActionPerformed
            catch(Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null, "KOTAK INPUT BELUM TERISI PENUH ", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
    }
    private void coba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coba1ActionPerformed
        nama1.setText("");
        tinggi1.setText("");
        berat1.setText("");
        jk.setText("");
        Ideal.setText("");
        ini1.setText("");
        ini2.setText("");
        cewek.setText("");
        lakii.setText("");
    }//GEN-LAST:event_coba1ActionPerformed

    private void keluarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarrActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField berat1;
    private javax.swing.JRadioButton cewek;
    private javax.swing.JButton coba1;
    private javax.swing.JButton hitung1;
    private javax.swing.JTextField ini1;
    private javax.swing.JTextField ini2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jk;
    private javax.swing.JButton keluarr;
    private javax.swing.JRadioButton lakii;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField tinggi1;
    // End of variables declaration//GEN-END:variables
}
